### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/explorer#2]
# Build

1. [x] Ideally needs updated PicoVector!
2. [x] Networking support
3. [x] Rebase!

# Examples

1. [ ] Basic analog oscilloscope/gauge
4. [x] Some kind of servo thing
5. [x] Sound/speaker example (PicoSystem little synth example?)
